//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebka.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int Id_academics { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string Speciality { get; set; }
        public Nullable<int> Year_of_the_title { get; set; }
    }
}
