//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebka.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gimnazists
    {
        public int Id { get; set; }
        public string Fname { get; set; }
        public string Object { get; set; }
        public string School { get; set; }
        public Nullable<double> Marks { get; set; }
    }
}
