//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebka.dbo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aeEntities : DbContext
    {
        public aeEntities()
            : base("name=aeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academics> Academics { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Disciplines> Disciplines { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Engineer> Engineer { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Gimnazists> Gimnazists { get; set; }
        public virtual DbSet<Pupils> Pupils { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Specialities> Specialities { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Zav_Kaf> Zav_Kaf { get; set; }
        public virtual DbSet<Животные_Баглай> Животные_Баглай { get; set; }
        public virtual DbSet<Страны_Баглай> Страны_Баглай { get; set; }
        public virtual DbSet<Управление_Баглай> Управление_Баглай { get; set; }
        public virtual DbSet<Цветы_Баглай> Цветы_Баглай { get; set; }
    }
}
