//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebka.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страны_Баглай
    {
        public int Id_Страны_Баглай { get; set; }
        public string country { get; set; }
        public string capital { get; set; }
        public string continent { get; set; }
        public string population { get; set; }
        public string square { get; set; }
        public string Id_Управление_Баглай { get; set; }
    }
}
